# Generated by Django 4.1.5 on 2023-01-27 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_age_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='first', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='last', max_length=50, verbose_name='Last name'),
        ),
    ]
