# Generated by Django 4.1.5 on 2023-01-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_first_name_alter_student_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='first_name_1',
        ),
    ]
