# Generated by Django 4.1.5 on 2023-02-03 19:12

import core.validators
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0005_rename_first_name_student_first_name_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[core.validators.ValidateEmailDomain('gmail.com', 'yahoo.com', 'test.com')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name_1',
            field=models.CharField(db_column='first', max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='"first_name" field value less then two symbols')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='last', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Last name'),
        ),
    ]
